name: HFA
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.7.0
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  rename: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
    - assets/images/hfalogos.png
    - assets/images/new.png


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/new.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/new.png"